#!/bin/sh

if [ ! -f test/network-monitor ]; then
	./autogen.sh && ./configure --enable-test && make
	if [ ! -f test/network-monitor ]; then
		echo
		echo "Compilation failed, cannot run network-monitor"
		echo
		exit 1
	fi
fi

GIO_EXTRA_MODULES=.libs test/network-monitor $*
